server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: inventory
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
      default-filters:
        - RemoveRequestHeader=Cookie
    loadbalancer:
      ribbon:
        enabled: false   # có thể bỏ nếu dùng Spring Cloud mới

  redis:
    host: redis
    port: 6379

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://auth-server/realms/demo

eureka:
  client:
    service-url:              # <-- phải là service-url (kebab-case), không phải serviceUrl
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
